### ISSUE TITLE
Dual monitor is still very buggy

### ISSUE THREAD

**Issue by BrushXue** [jimpalompa/OpenCore-Asus-Z170i-Pro-Gaming#5]
Thanks for the workaround. I have the same Motherboard, i7-6700K.

I had to disconnect the DP cable from both MB and monitor to make it work. If I only disconnect it from the MB, it's like ~50% it will be no signal, ~50% will hard reset.

**Comment by jimpalompa** [comment]
Yeah I'm aware of this. The release description says "Kinda glitchy though." ☹️

I'm soon gonna upgrade my build with a dedicated AMD GPU in the future, so there will be no more releases for dual displays on iGPU. Sorry.

**Comment by BrushXue** [comment]
Thanks. The current workaround is acceptable for me.

**Comment by BrushXue** [comment]
I just found something (use google translation): https://apple.sqlsec.com/6-实用姿势/6-13.html#华硕-asus
Looks like it's using a Mac mini SMBIOS.

**Comment by jimpalompa** [comment]
I'm not gonna go through the hassle getting dual displays on iGPU, my system crashed last time and I'm soon upgrading to a dedicated GPU. But please try it out yourself and reply if you have success 😃
